In [1]:
import numpy as np

In [72]:
import pandas as pd

## Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

Создать 5 двумерных массивов разной формы из массива a. 

Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [3]:
a = np.arange(12,24)

In [4]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [5]:
a1 = a.reshape(2,6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a2 = a.reshape(6,2)
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a3 = a.reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a4 = a.reshape(3,4)
a4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a5 = a.reshape(12,1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [10]:
a11 = a.reshape(-1,1)
a11


array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [11]:
a12 = a.reshape(-1,4)
a12

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a13 = a.reshape(-1,3)
a13

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a14 = a.reshape(6,-1)
a14

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [14]:
a15 = a.reshape(2,-1)
a15

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Массив из 12 строк но с одним столбцом является двумерным, элементы в массиве имееют два индекса, индекс строки и столбца.


## 2.
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 

Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [15]:
a2 = np.random.randn(3,4)
a2

array([[ 0.15913727, -0.05543226, -1.86630276,  0.89792866],
       [-0.33816645,  0.2443454 ,  0.05644821, -0.52192319],
       [ 1.10722058, -1.14810863,  1.09394652,  1.43655054]])

In [16]:
print(f'Size {a2.size}, ArrayShape: {a2.shape}')

Size 12, ArrayShape: (3, 4)


In [17]:
a2.size

12

In [18]:
a21 = a2.flatten()
a21

array([ 0.15913727, -0.05543226, -1.86630276,  0.89792866, -0.33816645,
        0.2443454 ,  0.05644821, -0.52192319,  1.10722058, -1.14810863,
        1.09394652,  1.43655054])

In [19]:
print(f'Size {a21.size}, ArrayShape: {a21.shape}')

Size 12, ArrayShape: (12,)


## 3.
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 

В чем разница между массивами a и b?


In [20]:
a31 = np.arange(20,0,-2)
a31

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [21]:
a32 = np.arange(20,1,-2).reshape(1,10)
a32

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Разница в том что массив а31 одномерный а массив а32 двумерный

## 4.
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [22]:
b4 = np.ones((2,2))

In [23]:
b4

array([[1., 1.],
       [1., 1.]])

In [24]:
a4 = np.zeros((3,2))

In [25]:
a4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
z = np.vstack((a4,b4))

In [27]:
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [28]:
z.size


10

## 5.
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.

Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.

Получить матрицу At путем транспонирования матрицы A.

Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [29]:
a5 = np.arange(0,12).reshape(4,3)

In [30]:
a5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
a5t = a5.transpose()

In [32]:
a5t

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [33]:
b5 = np.dot(a5,a5t)

In [34]:
b5

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

В результате умножения получается матрица 4х4 так как матрица а5 имеет размер (4х3) а её транспонированый вариант имеет размер (3х4)

In [35]:
np.linalg.det(b5)

0.0

Для матрицы b5 нельзя вычислить обратную матрицу не смотря на то что она квадратная, так как она вырожденая, её определитель равен 0.

## 6.
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. 
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [36]:
np.random.seed(42)

In [37]:
a6 = np.random.randint(0,16,16)

In [38]:
a6

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [39]:
c6 = a6.reshape((4,4))

In [40]:
c6

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [41]:
d6 = (b5 + c6)*10

In [42]:
d6


array([[ 110,  170,  350,  460],
       [ 240,  570,  980, 1260],
       [ 290,  950, 1510, 2180],
       [ 420, 1320, 2190, 3060]])

In [43]:
print(f'Определитель: {np.linalg.det(d6)}')

Определитель: -471960000.00000125


In [44]:
print(f'Ранг: {np.linalg.matrix_rank(d6)}')

Ранг: 4


In [45]:
d6_inv = np.linalg.inv(d6)
print(f'Обратная матрица: {d6_inv}')

Обратная матрица: [[ 0.01348843  0.0079583   0.01798881 -0.01812018]
 [-0.01714976  0.01400966  0.0147343  -0.0136876 ]
 [-0.00575896  0.00122044 -0.02040427  0.01489957]
 [ 0.00966819 -0.00800915  0.00577803 -0.00194508]]


## 7.
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.



In [46]:

for x in np.nditer(d6_inv):
    if x>0:       
       d6_inv[d6_inv == x] = 1
       
    else:
       d6_inv[d6_inv == x] = 0
       


In [47]:
d6_inv

array([[1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [48]:
c6

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [49]:
b5

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [50]:
E = np.where(d6_inv,b5,c6)

In [51]:
E

array([[  5,  14,  23,  14],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212,   4]])


## -------

## ------


## -----

## Задача 2

In [52]:
1
#### Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
#### Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
#### Будем считать, что каждый столбец - это признак, а строка - наблюдение.
#### Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
#### Результат запишите в массив mean_a, в нем должно быть 2 элемента.

a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [53]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [54]:
mean_a = np.mean(a,axis = 0)

In [55]:
mean_a

array([2. , 8.4])

In [56]:
2
#### Вычислите массив a_centered, отняв от значений массива а 
#### средние значения соответствующих признаков, содержащиеся в массиве mean_a.
#### Вычисление должно производиться в одно действие.
#### Получившийся массив должен иметь размер 5x2.

2

In [57]:
a_centered = a-mean_a

In [58]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [59]:
3
#### Найдите скалярное произведение столбцов массива a_centered.
#### В результате должна получиться величина a_centered_sp. 
#### Затем поделите a_centered_sp на N-1, где N - число наблюдений.

3

In [60]:
a1 = a_centered[:5,0]

In [61]:
b1 = a_centered[:5,1]

In [62]:
a1,b1

(array([-1.,  0.,  1.,  1., -1.]), array([-2.4, -0.4,  2.6,  1.6, -1.4]))

In [63]:
a_centered_sp = a1@b1

In [64]:
x = a_centered_sp/(a.shape[0]-1)

In [65]:
x

2.0

In [66]:
4
#### Число, которое мы получили в конце задания 3 является 
#### ковариацией двух признаков, содержащихся в массиве а.
#### В задании 3 мы делили сумму произведений центрированных 
#### признаков на N-1, а не на N, поэтому полученная нами величина 
#### является несмещенной оценкой ковариации.

#### В этом задании проверьте получившееся число, вычислив
#### ковариацию еще одним способом - с помощью функции np.cov.
#### В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
#### В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
#### ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

4

In [67]:
a_t = a.transpose()

In [68]:
a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [69]:
cov = np.cov(a_t)

In [70]:
cov[0,1]

2.0

In [71]:
#### Значение полученное в ходе выполнение пунктов 1-3 совпало со значением в пункте 4


## ---

## ---

## Задачи Pandas


Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. // От ученика - импортировано в начале файла

Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные:
[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

Затем создайте датафрейм book cо столбцами author_id, book_title и price,в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3],

['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [74]:
authors = pd.DataFrame({'author_id':[1,2,3],
                  'author_name':['Тургенев','Чехов','Островский']})

In [78]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [79]:
book  = pd.DataFrame({'author_id':[1,1,1,2,2,3,3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]})

In [80]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [84]:
authors_price = pd.merge(authors,book, on = 'author_id', how = 'inner')

In [85]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [107]:
top5 = authors_price.sort_values('price').tail(5)
top5

author_id author_name         book_title  price
2          1    Тургенев  Дворянское гнездо    350
5          3  Островский              Гроза    370
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
3          2       Чехов   Толстый и тонкий    500

In [106]:
top5 = authors_Price.nlargest(5,'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350


Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price.

В датафрейме authors_stat должны быть четыре столбца:

author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, 

максимальная и средняя цена на книги этого автора.


In [135]:
authors_stat = authors_price.groupby('author_name').agg({'price':'max'})

In [136]:
authors_stat = authors_stat.rename(columns = {'price':'max_price'})

In [137]:
min_price = authors_price.groupby('author_name').agg({'price':'min'}).rename(columns = {'price':'min_price'})
mean_price = authors_price.groupby('author_name').agg({'price':'mean'}).rename(columns = {'price':'mean_price'})


In [138]:

authors_stat = pd.merge(authors_stat,min_price, on = 'author_name',how = 'inner')
authors_stat = pd.merge(authors_stat,mean_price, on = 'author_name',how = 'inner')

In [139]:
authors_stat

max_price  min_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

Задание5

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая.

В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.

Используйте для этого функцию pd.pivot_table.

При этом столбцы должны называться "твердая" и "мягкая",а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,при необходимости загрузите библиотеку Numpy.

Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl".Затем загрузите из этого файла датафрейм и назовите его book_info2.Удостоверьтесь, что датафреймы book_info и book_info2 идентичны



In [144]:
authors_price['Обложка'] =  ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [145]:
authors_price

author_id author_name            book_title  price  Обложка
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [156]:
book_info = pd.pivot_table(authors_price,values = 'price',index = ['author_name'] ,columns = ['Обложка'], aggfunc = 'sum', fill_value = 0)

In [157]:
book_info

Обложка      мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [159]:
book_info.to_pickle('book_info.pkl')

In [160]:
book_info2 = pd.read_pickle('book_info.pkl')

In [161]:
book_info2

Обложка      мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950