In [38]:
import numpy as np


In [8]:
print("Hello")

Hello


In [16]:
a = [i for i in range(10)]

In [17]:
b = np.array(a)


In [23]:
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
type(b)

numpy.ndarray

In [30]:
b.ndim


1

In [35]:
b = np.array([i for i in range(15)], dtype = float)

In [37]:
b


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [49]:
b = np.array([[i for i in range(15)],[i for i in range(15)]])

In [51]:
b.shape

(2, 15)

In [70]:
b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [71]:
c = b[:2,:5].copy()

b



array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [72]:

c 


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [73]:
c

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Умножение матриц

In [87]:
x1 = np.array([[1,2],
               [3,4],
               [5,6]])
x2 = np.array([[7,8,9,10],
               [11,12,13,14]])

x1.shape, x2.shape

((3, 2), (2, 4))

In [91]:
x1.shape[1] == x2.shape[0]

True

In [92]:
c1 = np.dot(x1,x2)
c1

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [93]:

A = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])
C = np.dot(A,A)
C1 = np.linalg.matrix_power(A,2)

C, C1

(array([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]]), array([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]]))

Единичная матрица

In [102]:
I = np.eye(3)

In [96]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
A = np.array([[1,2],
             [3,4],
             [5,6]])

Умножение на единичную матрицу (дает исходную матрицу)

In [103]:
np.dot(I,A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Транспонирование матрицы

In [105]:
A = np.array([[1,2],
             [3,4],
             [5,6]])
At = A.T
At

array([[1, 3, 5],
       [2, 4, 6]])

In [108]:
At = A.transpose()

In [111]:
At

array([[1, 3, 5],
       [2, 4, 6]])

In [112]:
B = np.array([[0,1],
              [3,4],
              [6,7],
              [2,5]
             ])

In [114]:
A.shape[1], B.shape[0]

(2, 4)

In [115]:
B = B.T

In [116]:
A.shape[1], B.shape[0]

(2, 2)

In [117]:
np.dot(A,B)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

Определитель и ранг матрицы

In [118]:
A = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])

np.linalg.det(A)



0.0

In [119]:
np.linalg.matrix_rank(A)

2

Обратная матрица

In [121]:
B = np.array([[7,4,5],
             [8,3,2],
             [6,10,12]])
B_inv = np.linalg.inv(B)

In [280]:
np.dot(B_inv,B)

array([[ 1.00000000e+00,  1.66533454e-16,  3.33066907e-16],
       [-1.22124533e-15,  1.00000000e+00, -2.22044605e-16],
       [-4.44089210e-16,  0.00000000e+00,  1.00000000e+00]])

In [123]:
np.linalg.inv(B_inv)

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])


Автоматическое создание массивов


In [124]:
a = np.zeros((3,4))

In [125]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
a = np.arange(1,10) ## одномерный массив от 1 до 9

In [132]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Автоматическое создание массивов

In [135]:
a = np.zeros((3,4))
b = np.ones((3,4))

In [140]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Массив из последовательностей


In [145]:
np.arange(0,10) ## от нуля до 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
np.arange(0,10,2) ## с шагом 2

array([0, 2, 4, 6, 8])

In [148]:
np.arange(10,0,-1) ## обратная последовательность

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [152]:
np.linspace(0,10,100) ## последовательность с дробным шагом, третий аргумент это кол-во элементов,
                      ## тоже самое что и np.arange(0,10,0.1) но включая праву границу

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [153]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [154]:
np.logspace(0,3,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [155]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

Генерация случайных чисел

numpy.random.sample - случайные числа с равномерным распределением в промежутке [0.0,1.0)

In [157]:
np.random.sample() ## случайное число

0.6639397600272748

In [158]:
np.random.sample(3)

array([0.92637164, 0.02144902, 0.91013928])

In [159]:
np.random.sample((2,3)) ## двумерный массив

array([[0.94597129, 0.20274732, 0.50804881],
       [0.99847156, 0.99818368, 0.33673831]])

In [160]:
np.random.sample((48,64,3))

array([[[3.51082896e-01, 5.27615497e-01, 1.58800306e-01],
        [7.30112860e-01, 8.10511497e-01, 9.27341901e-01],
        [1.11499028e-02, 8.55389884e-01, 7.99711675e-01],
        ...,
        [3.39872249e-01, 5.96449156e-01, 9.31760443e-01],
        [1.55768668e-01, 1.88109855e-01, 9.27154245e-01],
        [4.94000742e-01, 7.22288513e-01, 5.21930652e-01]],

       [[1.17068690e-01, 2.61265188e-01, 6.36717961e-01],
        [5.17683101e-01, 8.61089067e-01, 8.32464869e-01],
        [1.73787790e-01, 8.30521263e-01, 3.87261371e-01],
        ...,
        [1.24624161e-01, 5.97684177e-01, 4.90753169e-01],
        [3.96746261e-01, 7.29315729e-01, 5.72157637e-01],
        [8.36370199e-01, 9.78183208e-01, 1.00786845e-01]],

       [[8.79936957e-01, 2.74441921e-01, 2.27193651e-01],
        [5.32436931e-01, 6.02783532e-01, 6.96746155e-01],
        [3.53076342e-01, 4.56671859e-01, 3.09004794e-01],
        ...,
        [3.41352457e-01, 4.32004726e-01, 4.68806155e-01],
        [2.50850537e-01, 4.46

numpy.random.randn ## случайные числа с нормальным распределением
(среднее значение = 0, среднеквадтратичное отклонение = 1)

In [162]:
np.random.randn(10)

array([ 0.76805221,  0.2902714 ,  1.99478218,  1.45473226, -1.58505964,
       -0.07583055,  1.52071776, -0.79332282,  0.57647774,  0.17753452])

In [163]:
np.random.randn(3,4)

array([[-1.21350114,  0.11688983,  0.88807537,  1.00779709],
       [ 1.5165642 ,  1.55403022, -0.08966535,  0.38004404],
       [-0.86152963, -0.03049628, -0.27581636, -1.2611794 ]])

In [169]:
b = np.random.randint(0,10,10)

In [170]:
b

array([5, 0, 5, 1, 9, 2, 5, 4, 0, 8])

In [171]:
a = np.random.randint(0,10,(3,4))

In [172]:
a

array([[3, 4, 3, 9],
       [4, 9, 2, 1],
       [0, 7, 9, 0]])

In [173]:
np.random.choice(b,3)

array([8, 5, 5])

In [174]:
np.random.choice(a[0],2)

array([4, 3])

In [177]:
b.reshape(2,5)

array([[5, 0, 5, 1, 9],
       [2, 5, 4, 0, 8]])

In [180]:
np.reshape(b,(2,-1))

array([[5, 0, 5, 1, 9],
       [2, 5, 4, 0, 8]])

In [181]:
b

array([5, 0, 5, 1, 9, 2, 5, 4, 0, 8])

In [182]:
b.resize(2,5)

In [183]:
b

array([[5, 0, 5, 1, 9],
       [2, 5, 4, 0, 8]])

In [185]:
b.flatten()

array([5, 0, 5, 1, 9, 2, 5, 4, 0, 8])

In [190]:
a = np.zeros((2,3))

In [196]:
b = np.ones((4,3))

In [197]:
v = np.vstack((a,b))

In [198]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [199]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [200]:
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [201]:
np.concatenate((a,b),axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [202]:
np.concatenate((a,b),axis = 1) 

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [204]:
b = np.ones((2,6))

In [205]:
np.concatenate((a,b), axis = 1)

array([[0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [207]:
np.hstack((a,b))

array([[0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [208]:
np.dstack([a,b])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [209]:
b = np.ones((2,3))

In [210]:
np.dstack([a,b])

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

# ВЫбор данных

In [211]:
a = np.random.randint(0,20,10)

In [212]:
a 

array([ 1,  9,  7,  9,  5, 16, 10,  0,  4,  4])

In [213]:
a[a>10]

array([16])

In [214]:
a[((a>10) & (a%2 == 0)) | (a%3 == 0)]

array([ 9,  9, 16,  0])

In [215]:
np.where(a > 7)

(array([1, 3, 5, 6], dtype=int64),)

In [217]:
a[np.where(a>7)]

array([ 9,  9, 16, 10])

In [221]:
a = [1,3,9,3,4]

In [222]:
b = [2,4,5,6,7]

In [223]:
c = np.where([True,False,True,False,False],a,b)

In [224]:
c

array([1, 4, 9, 6, 7])


## Сортировка

In [227]:
a = np.array([[1,3,9,9],
             [5,0,1,5],
             [2,7,3,5]])

In [228]:
a


array([[1, 3, 9, 9],
       [5, 0, 1, 5],
       [2, 7, 3, 5]])

In [230]:
a[[0,2,1],:]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [231]:
a[2:1]

array([], shape=(0, 4), dtype=int32)

In [233]:
a[[0,2],:]

array([[1, 3, 9, 9],
       [2, 7, 3, 5]])

In [234]:
a[0:2]

array([[1, 3, 9, 9],
       [5, 0, 1, 5]])

In [235]:
a[1:2]

array([[5, 0, 1, 5]])

In [236]:
a[1:]

array([[5, 0, 1, 5],
       [2, 7, 3, 5]])

In [240]:
a[[0],0:2]

array([[1, 3]])

In [241]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [242]:
a

array([[1, 3, 9, 9],
       [5, 0, 1, 5],
       [2, 7, 3, 5]])

In [243]:
a[:,0].argsort()

array([0, 2, 1], dtype=int64)

In [244]:
a[a[:,0].argsort(),:]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

## Математические действия с массивами

In [245]:
a = np.arange(1,7).reshape(2,3)

In [246]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [249]:
np.log(a) ## натуральный логарифм (логариф числа а по основанию е (2.72))

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [250]:
np.exp(a) ## экспонента exp(a) = e ^ a

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [254]:
b = np.arange(1,7).reshape(2,3)

In [255]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [256]:
a[:,0:1]

array([[1],
       [4]])

In [257]:
a[0,0]

1

In [258]:
a = np.array([[2,5],
              [3,4],
              [6,1]])

In [259]:
b = np.array([1,2])

In [260]:
a+b

array([[3, 7],
       [4, 6],
       [7, 3]])

In [262]:
c = np.array([[1],[2],[3]])

In [263]:
a+c

array([[3, 6],
       [5, 6],
       [9, 4]])

In [264]:
a = np.random.randint(0,12,(3,4))

In [265]:
a

array([[ 2,  6,  9,  4],
       [ 2,  9,  9,  6],
       [ 3,  2, 10,  2]])

In [266]:
a.min()

2

In [268]:
a.sum(axis = 1)

array([21, 26, 17])

In [269]:
a.mean()


5.333333333333333

In [270]:
a.mean(axis = 0)

array([2.33333333, 5.66666667, 9.33333333, 4.        ])

In [271]:
a.std()

3.091206165165235

In [272]:
a.std(axis = 0)

array([0.47140452, 2.86744176, 0.47140452, 1.63299316])

In [273]:
np.save('a.npy',a)

In [274]:
np.load('a.npy')

array([[ 2,  6,  9,  4],
       [ 2,  9,  9,  6],
       [ 3,  2, 10,  2]])

## PANDAS

In [2]:
import pandas as pd

In [3]:
a = [2,5,7,8,3]

In [4]:
b = pd.Series(a) ## создание объекта Series, слева индексы справа данные

In [5]:
b

0    2
1    5
2    7
3    8
4    3
dtype: int64

In [7]:
b = pd.Series(a,index = [4,3,2,1,0]) ## индексы можно задавать явно цифрами

In [8]:
b

4    2
3    5
2    7
1    8
0    3
dtype: int64

In [17]:
## так же индексы можно задавать буквами 
b = pd.Series(a, index = ['a','b','c','d','e'])

In [11]:
 
b

a    2
b    5
c    7
d    8
e    3
dtype: int64

In [19]:
from datetime import date


In [20]:
## В качстве индексов можно использовать и даты.
## Явно определяющие индексы можно передавать ввиде переменной с массивом значений которые будут использоваться в качстве индексов
ind = [date(y,m,d) for y,m,d in [(2018,1,15),(2018,1,17),(2018,1,19),(2018,1,22),(2018,1,27)]]

In [21]:
b = pd.Series(a,index = ind)

In [22]:
b

2018-01-15    2
2018-01-17    5
2018-01-19    7
2018-01-22    8
2018-01-27    3
dtype: int64

In [23]:
b.index


Index([2018-01-15, 2018-01-17, 2018-01-19, 2018-01-22, 2018-01-27], dtype='object')

In [29]:
## для типов object хранится ссылка на данные но не сами данные, поэтому можно выполнять присущие для данных операции например 
## как для даты выбор аттрибутов год, месяц, день, но только по элементно а не для всех элементов сразу.
b.index[0].year

2018

In [25]:
b.index[0].month

1

In [26]:
b.index[0].day

15

In [27]:
b.index = pd.to_datetime(b.index, format = '%Y-%m-%d') ## приведение типов обджект к типу дейттайм64 библиотеки пандас. 
## это даст возможность использовать присущие дате времени операции по всему индексу сразу (year,month,day)

In [28]:
b.index

DatetimeIndex(['2018-01-15', '2018-01-17', '2018-01-19', '2018-01-22',
               '2018-01-27'],
              dtype='datetime64[ns]', freq=None)

In [30]:
b.index.year

Int64Index([2018, 2018, 2018, 2018, 2018], dtype='int64')

In [31]:
b.index.month

Int64Index([1, 1, 1, 1, 1], dtype='int64')

In [32]:
b.index.day

Int64Index([15, 17, 19, 22, 27], dtype='int64')

Индексы могут быть не уникальными, и могут повторяться

In [34]:
b = pd.Series(a, index = [0,0,1,2,2])

In [35]:
b

0    2
0    5
1    7
2    8
2    3
dtype: int64

In [39]:
## Можно задавать тип данных

In [40]:
b = pd.Series(a,dtype = np.float64)

In [42]:
b 

0    2.0
1    5.0
2    7.0
3    8.0
4    3.0
dtype: float64

In [43]:
## поменять выбранный тип для уже созданного обьекта можно с помощью astype

In [45]:
b = b.astype(np.int64)

In [46]:
b

0    2
1    5
2    7
3    8
4    3
dtype: int64

Серии можно создавать из словарей, при этом ключи словаря станут индексами серии

In [50]:
a = {'1st':'a', '2nd':'b', '3rd':'c','4th':'d'}

In [51]:
b = pd.Series(a)

In [52]:
b

1st    a
2nd    b
3rd    c
4th    d
dtype: object

In [53]:
## просмотр данных.
b = pd.Series([5,2,6,1,6,8,7])

In [54]:
b.index

RangeIndex(start=0, stop=7, step=1)

In [55]:
b.values

array([5, 2, 6, 1, 6, 8, 7], dtype=int64)

доступ по индексу осуществляется аналогично словарю

In [56]:
b[2]

6

Доступ можно осуществлять по списку индексов, тогда в селектор передается список с нужными индексами



In [58]:
a

{'1st': 'a', '2nd': 'b', '3rd': 'c', '4th': 'd'}

In [59]:
b = pd.Series(a)

In [60]:
b['4th']

'd'

In [61]:
b[['1st','3rd','2nd']]

1st    a
3rd    c
2nd    b
dtype: object

In [62]:
## Для просмотра нескольких элементов от начала можно использовать head (b.head) или tail (b.tail).
## По умолчанию количество возвращаемых элементов = 5, можно указывать явно

In [63]:
b.head(1)

1st    a
dtype: object

In [64]:
b.tail(1)

4th    d
dtype: object

In [65]:
## Выборка по условию

In [66]:
b = pd.Series({1:'a',2:'a',3:'b',4:'c',5:'b'})

In [67]:
b

1    a
2    a
3    b
4    c
5    b
dtype: object

In [68]:
b[b=='a']

1    a
2    a
dtype: object

In [69]:
b[(b=='a')|(b=='c')]

1    a
2    a
4    c
dtype: object

In [70]:
## Изменение элементов аналогично изменению элементов в словаре

In [75]:
b[5] = 'c'  ## элемент с индексом 5 получил значение c

In [76]:
b

1    e
2    e
3    b
4    e
5    c
dtype: object

In [77]:
b[(b=='a')|(b=='c')] = 'e' ## элементы у которых данные равны а или c получили значение e

In [78]:
b

1    e
2    e
3    b
4    e
5    e
dtype: object

In [79]:
## добавление данных

In [82]:
b.append(pd.Series({6:'de',7:'cd',8:'c',9:'s'}))

1     e
2     e
3     b
4     e
5     e
6    de
7    cd
8     c
9     s
dtype: object

In [84]:
b.append(pd.Series(('de','cd','c','s')))

1     e
2     e
3     b
4     e
5     e
0    de
1    cd
2     c
3     s
dtype: object

In [85]:
b.append(pd.Series({'1st':'de','2nd':'cd','3rd':'c','4th':'s'}))

1       e
2       e
3       b
4       e
5       e
1st    de
2nd    cd
3rd     c
4th     s
dtype: object

In [86]:
## удаление данных осуществляется методом drop c указанием индексов которые надо удалить
b.drop([4,5])

1    e
2    e
3    b
dtype: object

In [87]:
b

1    e
2    e
3    b
4    e
5    e
dtype: object

In [88]:
## Запись и чтение данных из файла

In [89]:
b.to_pickle('b.pkl')

In [90]:
b2 = pd.read_pickle('b.pkl')

In [91]:
b2

1    e
2    e
3    b
4    e
5    e
dtype: object

## DataFrame

dataframe - двумерная структура данных библиотеки Pandas

In [94]:
df = pd.DataFrame({'Col1':['a','b','c','d','e','f','g','h'],
                  'Col2':[1,3,5,7,9,11,13,15]},columns = ['Col1','Col2'])

In [100]:
df


Col1  Col2
0    a     1
1    b     3
2    c     5
3    d     7
4    e     9
5    f    11
6    g    13
7    h    15

In [101]:
df.shape

(8, 2)

In [102]:
df.columns

Index(['Col1', 'Col2'], dtype='object')

In [103]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
Col1    8 non-null object
Col2    8 non-null int64
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [105]:
df.describe()

Col2
count   8.000000
mean    8.000000
std     4.898979
min     1.000000
25%     4.500000
50%     8.000000
75%    11.500000
max    15.000000

In [108]:
df.head(2)

Col1  Col2
0    a     1
1    b     3

In [110]:
df['Col1'].head()

0    a
1    b
2    c
3    d
4    e
Name: Col1, dtype: object

In [111]:
df.Col1.head()

0    a
1    b
2    c
3    d
4    e
Name: Col1, dtype: object

In [112]:
df.Col1

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
Name: Col1, dtype: object

In [113]:
df.tail

<bound method NDFrame.tail of   Col1  Col2
0    a     1
1    b     3
2    c     5
3    d     7
4    e     9
5    f    11
6    g    13
7    h    15>

In [114]:
## Изменение индекса

In [115]:
df.index = [2,4,6,8,10,12,14,16]

In [116]:
df

Col1  Col2
2     a     1
4     b     3
6     c     5
8     d     7
10    e     9
12    f    11
14    g    13
16    h    15

In [119]:
## выбор данных по индексу loc[index,column]

In [120]:
df.loc[2,'Col1']

'a'

In [121]:
df.loc[2,:]

Col1    a
Col2    1
Name: 2, dtype: object

In [124]:
df.loc[2,:].Col1 ## вернет данные по индексу 2 для всех колонок

'a'

In [125]:
df.loc[2:4,:] ## вернет данные с индексами от 2 до 4 для всех колонок

Col1  Col2
2    a     1
4    b     3

Выбор данных по позиции

In [127]:
df.iloc[0,:] ## выбор данных из 0 строки и обох столбцов

Col1    a
Col2    1
Name: 2, dtype: object

In [129]:
df.iloc[0:2,:] 
## вернет данные с 1 по 3ую строку не включая правую границу (тоесть 3ую строку. нумерация строк начинается от 0)
## обоих столбцов

Col1  Col2
2    a     1
4    b     3

In [130]:
df.iloc[0:2,0] ## вернет 1 и 2 строку первого столбца

2    a
4    b
Name: Col1, dtype: object

Выбор по условию

In [136]:
df.loc[(df['Col1'] == "b")|(df['Col1']== 'a'),:] ## Вернет только те строки у которых значение в колонке Col1 равны а или b

Col1  Col2
2    a     1
4    b     3

In [137]:
df.loc[(df['Col1'] == "b")|(df['Col1']== 'a'),'Col2'] ## Вернет строки только со значениям второй колонки, для которых значния первой колонки равны а или b

2    1
4    3
Name: Col2, dtype: int64

In [139]:
df.loc[(df['Col1'] == "b")|(df['Col1']== 'a'),:].values ## Values возвращает данные ввиде многомерного массива np.Array

array([['a', 1],
       ['b', 3]], dtype=object)

In [141]:
df.loc[df['Col2']>10,'Col1']

12    f
14    g
16    h
Name: Col1, dtype: object

In [142]:
df.loc[(df['Col1'] != "f")&(df['Col2'] >10),:]

Col1  Col2
14    g    13
16    h    15

In [144]:
df.loc[(df['Col1'] != "f")&(df['Col2'].between(1,14)),:]

Col1  Col2
2     a     1
4     b     3
6     c     5
8     d     7
10    e     9
14    g    13

In [148]:
df.loc[(df['Col1'].isin(['c','d','e','a']))&(df['Col2'].between(1,14)),:] 
## метод isin вернет нам только те значения что попадают в список

Col1  Col2
2     a     1
6     c     5
8     d     7
10    e     9

In [150]:
df.loc[~(df['Col1'].isin(['c','d','e','a']))&(df['Col2'].between(1,14)),:] 
## ~ означет не, перед isin получится только те елементы что не попадают в этот список

Col1  Col2
4     b     3
12    f    11
14    g    13

Метод Query

In [152]:
df.query('Col1 == "b"') ## все элементы датафрейма у которых столбец Col1 = b

Col1  Col2
4    b     3

Когда выбирается только один столбец из дата фрейма мы получаем обьект типа Series

In [154]:
s = df['Col1']

In [155]:
s

2     a
4     b
6     c
8     d
10    e
12    f
14    g
16    h
Name: Col1, dtype: object

In [156]:
type(s)

pandas.core.series.Series

## Получение DataFrame из Series

In [157]:
df2 = pd.DataFrame(s)

In [158]:
df2

Col1
2     a
4     b
6     c
8     d
10    e
12    f
14    g
16    h

## Копирование датафрайем


In [159]:
## Осуществляется обязательно с применением метода copy

In [160]:
df_copy = df.copy()

In [161]:
df_copy

Col1  Col2
2     a     1
4     b     3
6     c     5
8     d     7
10    e     9
12    f    11
14    g    13
16    h    15

## Случайный выбор n-го количества строк

In [162]:
df.sample(n = 2) ## аргумент n означает количество строк

Col1  Col2
6    c     5
8    d     7

In [163]:
df.sample(n = 2)

Col1  Col2
2    a     1
8    d     7

## Случайный выбор доли от исходного датафрейма

In [164]:
df.sample(frac = 0.5) ## аргумент фрак означет долю строк от общего кол-ва строк

Col1  Col2
14    g    13
4     b     3
2     a     1
8     d     7

## Случайный выбор с возвращением (строки могут повторяться)

In [167]:
df.sample(frac = 0.6, replace = True)

Col1  Col2
16    h    15
12    f    11
12    f    11
14    g    13
8     d     7

## Запись и чтение данных из файла (используемый формат csv)

In [171]:
df.to_csv('Test.csv',sep = ';',index = False) ## sep - разделитель, index - писать индекс датафрейма в файл или нет


In [169]:
df_new = pd.read_csv('Test.csv', sep = ';')

In [170]:
df_new

Col1  Col2
0    a     1
1    b     3
2    c     5
3    d     7
4    e     9
5    f    11
6    g    13
7    h    15

Так же можно писать данные в формат excel и pickle для этого используются методы to_excel,to_pickle,чтение read_excel,read_pickle

## Слияние данных

In [172]:
authors = pd.DataFrame({'author_id':[1,2,3],
                  'author_name':['Тургенев','Чехов','Островский']})

book  = pd.DataFrame({'author_id':[1,1,1,2,2,3,3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]})

In [173]:
authors


author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [174]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [176]:
## Для слияния двух датафреймов можно использовать функцию merge
book_authors = pd.merge(authors,book, on = 'author_id', how = 'inner')

In [177]:
book_authors

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290